### ISSUE TITLE
g

### ISSUE THREAD

**Issue by noimno** [notzastix/blacket-hacks#46]
ＩＦ ＹＯＵ ＡＲＥ ＲＥＡＤＩＮＧ ＴＨＩＳ ＴＨＥＮ ＹＯＵ ＷＩＬＬ ＤＩＥ ＩＮ ＹＯＵＲ ＳＬＥＥＰ ＴＯＮＩＧＨＴ. ＩＦ ＹＯＵ ＣＯＰＹ ＴＨＩＳ ＯＮ ＡＮＯＴＨＥＲ COMMENT SECTION , ＹＯＵ ＷＩＬＬ ＨＡＶＥ ＧＯＯＤ ＬＵＣＫ ＦＯＲＥＶＥＲ

**Comment by XOTlC** [comment]
https://media.discordapp.net/attachments/952969140711325749/967645496858542090/bia_goof_2.gif

**Comment by XOTlC** [comment]
[https://media.discordapp.net/attachments/952969140711325749/967645496858542090/bia_goof_2.gif](url)
