### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by TheVillainCoder** [notzastix/blacket-hacks#50]
Are those keyboard shortcuts for all operating systems? Including a Mac?

**Comment by FallGuysFan1234** [comment]
Most likely, but lets wait for zastix to answer :D

**Comment by TheVillainCoder** [comment]
@FallGuysFan1234 Macs usually use the command button instead of the control, that's why I'm wondering.

**Comment by FallGuysFan1234** [comment]
> @FallGuysFan1234 Macs usually use the command button instead of the control, that's why I'm wondering.

Oh ok! :D

**Comment by notzastix** [comment]
> Are those keyboard shortcuts for all operating systems? Including a Mac?

yeah, they should be
