### ISSUE TITLE
Hey Sugestion 

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [notzastix/blacket-hacks#58]
Are you able to make a script that can show you what you can get from the boxes?

**Comment by notzastix** [comment]
good idea, ill do that

**Comment by Snowflake-Coder-H2o** [comment]
@notzastix Alright Thank you.

**Comment by Snowflake-Coder-H2o** [comment]
@notzastix How long will it be until it is made?

**Comment by notzastix** [comment]
xotic has done this

**Comment by Snowflake-Coder-H2o** [comment]
@notzastix ya I see
