### ISSUE TITLE
Spam Open Crates doesn't work

### ISSUE THREAD

**Issue by FallGuysFan1234** [notzastix/blacket-hacks#60]
This is just a simple issue really, the Spam Open Boxes hack doesnt work 😭

**Comment by FallGuysFan1234** [comment]
Here's what happens when I try to use it:
![image](https://user-images.githubusercontent.com/92480033/168479985-57325d95-c32b-483e-92c9-81aea2676c0a.png)

**Comment by FallGuysFan1234** [comment]
I hope you are able to fix it :D

**Comment by notzastix** [comment]
This, is because you ran the script twice without reloading, ill add support for multiple runs in a session, thanks for telling me!
