### ISSUE TITLE
zastix please listen to this!

### ISSUE THREAD

**Issue by FallGuysFan1234** [notzastix/blacket-hacks#68]
Hey zastix! I noticed you had alot of typos in this betastar repo, so I forked your repo and fixed all of the typos in it + some extra things! If you wanna check it out the link is here: https://github.com/FallGuysFan1234/betastar-hacks
I hope this will help you fix all the typos in this current repo :D
(Also the "extra things" I added are just alot of exclamation marks lol)

**Comment by Hankypoo7** [comment]
make a pull request

**Comment by FallGuysFan1234** [comment]
> make a pull request

How do I do that? Its kind of hard for me to understand it, but I know where to start at least :D

**Comment by FallGuysFan1234** [comment]
> make a pull request

I know where to make a pull request, but how do I do it? Its hard for me to understand and idk where to find the branches and tags D:

**Comment by FallGuysFan1234** [comment]
Wait never mind I figured out how to make one! :D
