### ISSUE TITLE
I'm happy to help you zastix!

### ISSUE THREAD

**Issue by FallGuysFan1234** [notzastix/blacket-hacks#75]
I just saw on your repo that you had fixed all of the typos with the help of me and @VillainsRule4000, so im just saying that im happy to help you and so is VillainsRule probably! :D

**Comment by notzastix** [comment]
Np, please don't open issues that aren't real issues, that's why theirs a discussion paye

**Comment by FallGuysFan1234** [comment]
> Np, please don't open issues that aren't real issues, that's why theirs a discussion paye

Alright, got it! :D
